kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.12
  environment:
    CGO_ENABLED: "0"
  commands:
  - go build
  - go test ./...

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: {{DockerRepository}}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
